export const HANDLE_INPUT = 'HANDLE_INPUT';
export const HANDLE_RESET_STATE = 'HANDLE_RESET_STATE';

export const GET_EDAMAM_RECIPES_BEGIN = 'GET_EDAMAM_RECIPES_BEGIN';
export const GET_EDAMAM_RECIPES_SUCCESS = 'GET_EDAMAM_RECIPES_SUCCESS';

export const GET_DRINKS_RECIPES_BEGIN = 'GET_DRINKS_RECIPES_BEGIN';
export const GET_DRINKS_RECIPES_SUCCESS = 'GET_DRINKS_RECIPES_SUCCESS';

export const SEND_MESSAGE_BEGIN = 'SEND_MESSAGE_BEGIN';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';


