export const HANDLE_INPUT = 'HANDLE_INPUT';

export const GET_EDAMAM_RECIPES_BEGIN = 'GET_EDAMAM_RECIPES_BEGIN';
export const GET_EDAMAM_RECIPES_SUCCESS = 'GET_EDAMAM_RECIPES_SUCCESS';

export const GET_DRINKS_RECIPES_BEGIN = 'GET_DRINKS_RECIPES_BEGIN';
export const GET_DRINKS_RECIPES_SUCCESS = 'GET_DRINKS_RECIPES_SUCCESS';

